name: build-and-test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "2.7"
          - "3.4"
          - "3.5"
          - "3.6"
          - "3.7"
          - "3.8"
          - "pypy2"
          - "pypy3"
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install pylama codecov

    - name: Code Coverage
      if: ${{ matrix.python-version != 'pypy2' && matrix.python-version != '2.7'  }}
      run: |
        coverage run \
        --source='../../updatable' --omit='../../updatable/__version__.py,../../updatable/__main__.py'  run_tests.py \
        && echo 'exit code '$?
        coverage xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1

    - name: Lint and test with pylama
      if: ${{ matrix.python-version != 'pypy2' && matrix.python-version != '2.7'  }}
      run: |
        pylama ../../updatable ../../test

    - name: Setup environment
      run: |
        python setup.py install
