name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "pypy3.7"
          - "pypy3.8"
          - "pypy3.9"
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install codecov black

    - name: Lint with black
      run: black ./updatable ./test --check

    - name: Setup environment
      run: python setup.py install

    - name: Code Coverage
      run: |
        coverage run --source='./updatable' --omit='./updatable/__main__.py'  run_tests.py
        coverage xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
